import type { Lang } from "@/lib/aura-landing/copy";
import type { ModuleKey } from "./catalog";

// Tüm metinler statiktir; sağlık verisi veya çeviri API çağrısı içermez.
type ModuleText = {
  name: string; title: string; description: string; focus: string;
  topics: [string, string, string];
  steps: [string, string, string];
  note: string; cta: string;
};
type CommonText = {
  discover: string; process: string; processIntro: string; focus: string;
  faq: string; questions: [string, string]; answers: [string, string];
  next: string; nextBody: string; other: string; privacy: string;
  imageNotice: string; skip: string;
};

export const COMMON: Record<Lang, CommonText> = {
  tr: { discover: "Süreci keşfedin", process: "Bir sonraki adımınız belli olsun.", processIntro: "İlk başvurudan sonraki karara, süreci birlikte netleştirelim.", focus: "Size nasıl yardımcı olabiliriz?", faq: "Aklınızdaki sorular", questions: ["Başvurudan sonra ne olur?", "Tıbbi belgelerimi nereden paylaşırım?"], answers: ["AURA hesabınız üzerinden ilgili başvuruyu tamamlarsınız. Değerlendirme ve sonraki adımlar, ihtiyacınıza ve klinik uygunluğa göre belirlenir.", "Belgeler yalnızca hesabınızdaki ilgili başvuru alanından paylaşılır. Erişim ve veri işleme ayrıntılarını Güven ve Gizlilik sayfasında inceleyebilirsiniz."], next: "İlk adımı birlikte atalım.", nextBody: "İhtiyacınızı anlatın. Size uygun sonraki adımı değerlendirin.", other: "AURA ile diğer bakım seçenekleri", privacy: "Güven ve gizlilik", imageNotice: "Yapay zekâ ile üretilmiş temsili görsel", skip: "İçeriğe geç" },
  en: { discover: "Explore the process", process: "Know what comes next.", processIntro: "From your first request to your next decision, understand each step.", focus: "How can we help?", faq: "Your questions, answered", questions: ["What happens after I apply?", "Where do I share my medical records?"], answers: ["Complete the relevant request through your AURA account. Assessment and next steps depend on your needs and clinical suitability.", "Share records only through the relevant application in your account. See Trust and Privacy for information about access and data processing."], next: "Let’s take the first step.", nextBody: "Tell us what you need. Explore the next step that suits you.", other: "Other ways to begin with AURA", privacy: "Trust and privacy", imageNotice: "AI-generated illustrative image", skip: "Skip to content" },
  de: { discover: "Ablauf ansehen", process: "Wissen, wie es weitergeht.", processIntro: "Von Ihrer ersten Anfrage bis zur nächsten Entscheidung: jeden Schritt verstehen.", focus: "Wie können wir helfen?", faq: "Ihre Fragen", questions: ["Was passiert nach meiner Anfrage?", "Wo teile ich meine medizinischen Unterlagen?"], answers: ["Füllen Sie die passende Anfrage in Ihrem AURA-Konto aus. Die Beurteilung und die nächsten Schritte richten sich nach Ihrem Bedarf und der medizinischen Eignung.", "Teilen Sie Unterlagen nur im jeweiligen Antragsbereich Ihres Kontos. Informationen zu Zugriff und Datenverarbeitung finden Sie unter Vertrauen und Datenschutz."], next: "Gehen wir den ersten Schritt.", nextBody: "Beschreiben Sie Ihren Bedarf und prüfen Sie den passenden nächsten Schritt.", other: "Weitere Möglichkeiten mit AURA", privacy: "Vertrauen und Datenschutz", imageNotice: "KI-generiertes Symbolbild", skip: "Zum Inhalt" },
  fr: { discover: "Découvrir le parcours", process: "Comprendre la prochaine étape.", processIntro: "De votre première demande à votre prochaine décision, un parcours expliqué.", focus: "Comment pouvons-nous vous aider ?", faq: "Vos questions", questions: ["Que se passe-t-il après ma demande ?", "Où partager mes documents médicaux ?"], answers: ["Complétez la demande correspondante dans votre compte AURA. L’évaluation et les étapes suivantes dépendent de vos besoins et de votre situation clinique.", "Partagez vos documents uniquement dans l’espace dédié de votre compte. Consultez Confiance et confidentialité pour les détails sur l’accès et le traitement des données."], next: "Faisons le premier pas.", nextBody: "Décrivez vos besoins. Explorez la prochaine étape adaptée à votre situation.", other: "D’autres parcours avec AURA", privacy: "Confiance et confidentialité", imageNotice: "Image illustrative générée par IA", skip: "Aller au contenu" },
  ru: { discover: "Узнать о процессе", process: "Понимать следующий шаг.", processIntro: "От первого обращения до следующего решения — понятный путь.", focus: "Чем мы можем помочь?", faq: "Ваши вопросы", questions: ["Что происходит после подачи заявки?", "Где передать медицинские документы?"], answers: ["Заполните соответствующую заявку в аккаунте AURA. Оценка и дальнейшие шаги зависят от ваших потребностей и клинической ситуации.", "Передавайте документы только в разделе соответствующей заявки в аккаунте. Об условиях доступа и обработки данных читайте на странице доверия и конфиденциальности."], next: "Сделаем первый шаг вместе.", nextBody: "Расскажите о своих потребностях и рассмотрите следующий шаг.", other: "Другие возможности AURA", privacy: "Доверие и конфиденциальность", imageNotice: "Иллюстрация создана ИИ", skip: "Перейти к содержимому" },
  ar: { discover: "تعرّف على الخطوات", process: "اعرف خطوتك التالية.", processIntro: "من طلبك الأول إلى قرارك التالي، افهم كل خطوة.", focus: "كيف يمكننا مساعدتك؟", faq: "أسئلتك", questions: ["ماذا يحدث بعد تقديم الطلب؟", "أين أشارك مستنداتي الطبية؟"], answers: ["أكمل الطلب المناسب عبر حسابك في AURA. يعتمد التقييم والخطوات التالية على احتياجاتك وملاءمة حالتك طبياً.", "شارك المستندات فقط في قسم الطلب المعني داخل حسابك. راجع صفحة الثقة والخصوصية لمعرفة تفاصيل الوصول ومعالجة البيانات."], next: "لنبدأ الخطوة الأولى معاً.", nextBody: "أخبرنا باحتياجاتك واستكشف الخطوة المناسبة لك.", other: "خيارات رعاية أخرى مع AURA", privacy: "الثقة والخصوصية", imageNotice: "صورة توضيحية مولّدة بالذكاء الاصطناعي", skip: "انتقل إلى المحتوى" },
  fa: { discover: "آشنایی با مراحل", process: "گام بعدی را بشناسید.", processIntro: "از نخستین درخواست تا تصمیم بعدی، هر مرحله را بشناسید.", focus: "چگونه می‌توانیم کمک کنیم؟", faq: "پرسش‌های شما", questions: ["پس از ثبت درخواست چه می‌شود؟", "مدارک پزشکی را کجا به اشتراک بگذارم؟"], answers: ["درخواست مربوط را در حساب AURA خود تکمیل کنید. ارزیابی و مراحل بعدی به نیازها و شرایط بالینی شما بستگی دارد.", "مدارک را فقط در بخش درخواست مربوط در حساب خود به اشتراک بگذارید. جزئیات دسترسی و پردازش داده‌ها در صفحه اعتماد و حریم خصوصی آمده است."], next: "گام اول را با هم برداریم.", nextBody: "نیازتان را بگویید و گام بعدی مناسب را بررسی کنید.", other: "دیگر گزینه‌های مراقبت با AURA", privacy: "اعتماد و حریم خصوصی", imageNotice: "تصویر نمایشی ساخته‌شده با هوش مصنوعی", skip: "رفتن به محتوا" },
  az: { discover: "Prosesi öyrənin", process: "Növbəti addımınız aydın olsun.", processIntro: "İlk müraciətdən növbəti qərara qədər hər addımı anlayın.", focus: "Sizə necə kömək edə bilərik?", faq: "Suallarınız", questions: ["Müraciətdən sonra nə baş verir?", "Tibbi sənədlərimi harada paylaşım?"], answers: ["AURA hesabınızda uyğun müraciəti tamamlayın. Qiymətləndirmə və növbəti addımlar ehtiyacınıza və klinik uyğunluğa görə müəyyən edilir.", "Sənədləri yalnız hesabınızdakı müvafiq müraciət bölməsində paylaşın. Giriş və məlumatların emalı barədə Etibar və məxfilik səhifəsinə baxın."], next: "İlk addımı birlikdə ataq.", nextBody: "Ehtiyacınızı bildirin və uyğun növbəti addımı qiymətləndirin.", other: "AURA ilə digər qayğı seçimləri", privacy: "Etibar və məxfilik", imageNotice: "Süni intellektlə yaradılmış təsviri görüntü", skip: "Məzmuna keç" },
  bg: { discover: "Разгледайте процеса", process: "Знайте следващата стъпка.", processIntro: "От първото запитване до следващото решение — разберете всяка стъпка.", focus: "Как можем да помогнем?", faq: "Вашите въпроси", questions: ["Какво следва след заявката?", "Къде да споделя медицинските си документи?"], answers: ["Попълнете съответната заявка в профила си в AURA. Оценката и следващите стъпки зависят от нуждите ви и клиничната ви ситуация.", "Споделяйте документи само в съответния раздел на заявката в профила си. Вижте страницата за доверие и поверителност за достъпа и обработката на данни."], next: "Нека направим първата стъпка.", nextBody: "Разкажете ни за нуждите си и разгледайте подходящата следваща стъпка.", other: "Други възможности с AURA", privacy: "Доверие и поверителност", imageNotice: "Илюстративно изображение, създадено с ИИ", skip: "Към съдържанието" },
};

// Sıra: ad, başlık, açıklama, odak metni, üç konu, üç adım, kapsam notu, eylem.
type Row = [string, string, string, string, [string, string, string], [string, string, string], string, string];
const rows: Record<Lang, Record<ModuleKey, Row>> = {
  tr: {
    "second-opinion": ["İkinci Görüş", "Kararınızdan önce, bir uzman görüşü daha.", "Tanınızı ve tedavi seçeneklerinizi yeniden değerlendirin. Belgelerinizi paylaşın; uzman değerlendirmesi, yazılı görüş ve video görüşmeyle sorularınızı netleştirin.", "Yeni bir tanı, önerilen bir tedavi veya aklınızda kalan sorular. Mevcut dosyanıza başka bir uzman bakışı kazandırın.", ["Mevcut tanıyı anlamak", "Tedavi seçeneklerini değerlendirmek", "Uzmanınıza sorularınızı sormak"], ["Tanınızı ve tıbbi belgelerinizi paylaşın.", "Uzman dosyanızı incelesin; gerekirse ek bilgi istesin.", "Yazılı görüşü ve video görüşmede ele alınan seçenekleri değerlendirin."], "İkinci Görüş mevcut tedavinizin veya acil sağlık hizmetinin yerine geçmez. Tıbbi karar, klinik değerlendirmeye dayanır.", "İkinci Görüşe başvur"],
    "medical-tourism": ["Sağlık Turizmi", "Tedaviniz için bir yol. Her adımda bir plan.", "Önce branş doktoruyla görüşün veya doğrudan Sağlık Turizmi talebi oluşturun. AURA’da yapay zekâ destekli branş önerisi, doktor değerlendirmesi ve acente teklifiyle sonraki adımınızı netleştirin.", "AURA’da iki başlangıç yolu, ihtiyacınız etrafında şekillenen bir süreç: branş seçimi, doktor görüşmesi, tedavi planı ve teklif.", ["Değiştirebileceğiniz yapay zekâ destekli branş önerisi", "Doktorla görüşme ve klinik değerlendirme", "Tedavi planına dayalı acente teklifi"], ["İhtiyacınızı anlatın; önerilen branşı inceleyip seçiminizi yapın.", "Doktorla seçenekleri değerlendirin; uygunsa tedavi planınız hazırlansın.", "Acente teklifinin kapsamını inceleyin; devam edip etmeyeceğinize karar verin."], "İlk talepte ödeme veya rezervasyon yapılmaz. Tedavinin uygunluğu, kapsamı ve fiyatı değerlendirme sonrasında belirlenir; seyahat hizmetleri teklif kapsamına bağlıdır.", "Tedavi talebi oluştur"],
    "medical-aesthetics": ["Medikal Estetik", "Size ait bir karar. Size uygun bir yaklaşım.", "AURA’da önce branş doktoruyla görüşün veya Medikal Estetik değerlendirmesi isteyin. Hedefinizi anlatın, branş önerisini inceleyin; doktor değerlendirmesinden sonra kişisel planınızı ve varsa seyahat teklifinizi ele alın.", "AURA, beklentinizi ilgili branşla buluşturur. İşlem kararı klinik değerlendirmeyle, seyahat ve hizmet kapsamı size sunulan planla netleşir.", ["Hedefinize göre branş seçimi", "Doktorla seçenekler ve uygunluk değerlendirmesi", "Kişisel plan, teklif kapsamı ve takip"], ["Ortak tedavi talebi formunda hedefinizi anlatın; önerilen branşı kontrol edin.", "Gelen mesaj ve görüşme önerilerini izleyin; doktorla seçenekleri değerlendirin.", "Uygunsa hazırlanan planı ve teklifi inceleyin; kararınızı kendiniz verin."], "İşlem ve sonuçlar kişiye göre değişir. Bu sayfa bir sonuç garantisi veya belirli bir işlemin sizin için uygun olduğuna dair öneri değildir.", "Değerlendirme talep et"],
  },
  en: {
    "second-opinion": ["Second Opinion", "Another expert perspective. Before your next decision.", "Revisit your diagnosis and treatment options. Share your records and clarify your questions through specialist review, a written opinion and a video consultation.", "A new diagnosis, a proposed treatment, or questions that remain. Bring another specialist’s perspective to your existing records.", ["Understand your diagnosis", "Consider treatment options", "Ask your specialist questions"], ["Share your diagnosis and medical records.", "A specialist reviews your file and may request more information.", "Consider the written opinion and the options discussed in your video consultation."], "A second opinion does not replace your current treatment or emergency care. Medical decisions depend on clinical assessment.", "Request a second opinion"],
    "medical-tourism": ["Medical Tourism", "A path to treatment. A plan for every step.", "Start with a specialist consultation or submit a Medical Tourism request directly. AURA connects AI-assisted specialty suggestions, doctor assessment and an agency proposal to help clarify your next step.", "Two ways to begin with AURA, one process shaped around your needs: specialty selection, consultation, treatment planning and a proposal.", ["AI-assisted specialty suggestions you can change", "Doctor consultation and clinical assessment", "An agency proposal based on the treatment plan"], ["Describe your needs, review the suggested specialty and make your selection.", "Discuss options with a doctor; a treatment plan follows where appropriate.", "Review the agency proposal and decide whether to proceed."], "No payment or reservation is made with the initial request. Suitability, scope and price follow assessment; travel services depend on the proposal.", "Start a treatment request"],
    "medical-aesthetics": ["Medical Aesthetics", "Your decision. An approach that fits you.", "Start with a specialist consultation or request a Medical Aesthetics assessment through AURA. Describe your goals and review the specialty suggestion; consider your individual plan and any travel proposal after clinical assessment.", "AURA connects your goals with the relevant specialty. Clinical assessment informs procedure decisions, while your proposed plan clarifies travel and service scope.", ["Specialty selection based on your goals", "Discussing options and suitability with a doctor", "Individual plan, proposal scope and follow-up"], ["Describe your goals in the shared treatment request form and review the suggested specialty.", "Follow messages and consultation proposals, then discuss options with a doctor.", "Review any appropriate plan and proposal, and make your own decision."], "Procedures and outcomes vary by person. This page does not guarantee results or recommend a particular procedure for you.", "Request an assessment"],
  },
  de: {
    "second-opinion": ["Zweitmeinung", "Eine weitere Fachmeinung. Vor Ihrer Entscheidung.", "Lassen Sie Diagnose und Behandlungsmöglichkeiten erneut beurteilen. Teilen Sie Ihre Unterlagen und klären Sie Fragen durch fachärztliche Prüfung, schriftliche Einschätzung und Videogespräch.", "Eine neue Diagnose, eine vorgeschlagene Behandlung oder offene Fragen: eine weitere fachärztliche Perspektive auf Ihre Unterlagen.", ["Diagnose verstehen", "Behandlungsmöglichkeiten abwägen", "Fragen an Fachärzte stellen"], ["Teilen Sie Ihre Diagnose und Unterlagen.", "Ein Facharzt prüft die Akte und fordert bei Bedarf weitere Angaben an.", "Prüfen Sie die schriftliche Einschätzung und die im Videogespräch besprochenen Optionen."], "Eine Zweitmeinung ersetzt weder Ihre laufende Behandlung noch die Notfallversorgung. Medizinische Entscheidungen erfordern eine klinische Beurteilung.", "Zweitmeinung anfragen"],
    "medical-tourism": ["Medizintourismus", "Ein Weg zur Behandlung. Ein Plan für jeden Schritt.", "Prüfen Sie Behandlungsmöglichkeiten in der Türkei. Ihre gesundheitlichen Bedürfnisse stehen am Anfang; Behandlung und Reise werden nach der klinischen Beurteilung geplant.", "Vom Behandlungsbedarf bis zur Nachsorge nach der Rückkehr: verstehen Sie die einzelnen Schritte.", ["Behandlungsgebiet und ärztliche Beurteilung", "Angebot, Unterkunft und Transfers", "Planung der Nachsorge"], ["Beschreiben Sie Ihren Bedarf und Ihre Wünsche.", "Prüfen Sie Angebote nach der ärztlichen Beurteilung.", "Klären Sie die geeignete Behandlung und Reiseorganisation."], "Die erste Anfrage löst keine Zahlung oder Buchung aus. Eignung, Umfang und Preis werden nach der Beurteilung bestimmt; Reiseleistungen richten sich nach dem Angebot.", "Behandlung anfragen"],
    "medical-aesthetics": ["Ästhetische Medizin", "Ihre Entscheidung. Ein passender Ansatz.", "Besprechen Sie Ihre ästhetischen Ziele mit einem Arzt. Informieren Sie sich über Möglichkeiten, Grenzen und Erholung, bevor Sie entscheiden.", "Ihre Erwartungen stehen am Anfang. Ein geeigneter Ansatz erfordert eine persönliche Beurteilung.", ["Hautbild und persönliche Ziele", "Eignung und mögliche Risiken", "Pflege und Erholung"], ["Beschreiben Sie Ihre Ziele im Anfrageformular.", "Besprechen Sie Möglichkeiten und Eignung mit einem passenden Facharzt.", "Klären Sie Plan, Risiken und Nachsorge vor Ihrer Entscheidung."], "Verfahren und Ergebnisse unterscheiden sich individuell. Diese Seite garantiert keine Ergebnisse und empfiehlt Ihnen keinen bestimmten Eingriff.", "Beurteilung anfragen"],
  },
  fr: {
    "second-opinion": ["Deuxième avis", "Un autre regard expert. Avant votre décision.", "Réexaminez votre diagnostic et les options de traitement. Partagez vos documents et clarifiez vos questions grâce à une évaluation spécialisée, un avis écrit et une consultation vidéo.", "Un nouveau diagnostic, un traitement proposé ou des questions en suspens : apportez un autre regard spécialisé à votre dossier.", ["Comprendre votre diagnostic", "Évaluer les options de traitement", "Poser vos questions au spécialiste"], ["Partagez votre diagnostic et vos documents.", "Un spécialiste examine le dossier et peut demander des informations complémentaires.", "Examinez l’avis écrit et les options abordées en consultation vidéo."], "Un deuxième avis ne remplace ni votre traitement actuel ni les soins d’urgence. Les décisions médicales reposent sur une évaluation clinique.", "Demander un deuxième avis"],
    "medical-tourism": ["Tourisme médical", "Un parcours de soins. Chaque étape se prépare.", "Explorez les possibilités de traitement en Turquie. Commençons par vos besoins de santé ; les soins et le voyage se préparent après l’évaluation clinique.", "Des besoins de traitement au suivi après votre retour, comprenez chaque étape.", ["Spécialité et évaluation médicale", "Proposition, hébergement et transferts", "Organisation du suivi"], ["Décrivez vos besoins et vos préférences.", "Examinez les propositions après l’évaluation médicale.", "Précisez les soins appropriés et les modalités du voyage."], "La demande initiale n’entraîne ni paiement ni réservation. L’adéquation, le périmètre et le prix sont précisés après évaluation ; les services de voyage dépendent de la proposition.", "Faire une demande de traitement"],
    "medical-aesthetics": ["Médecine esthétique", "Votre décision. Une approche adaptée à vous.", "Discutez de vos objectifs esthétiques avec un médecin. Comprenez les options, les limites et la récupération avant de décider.", "Vos attentes sont le point de départ. Une approche adaptée nécessite une évaluation individuelle.", ["Aspect de la peau et objectifs personnels", "Adéquation et risques possibles", "Soins et récupération"], ["Décrivez vos objectifs dans le formulaire.", "Discutez des options et de leur adéquation avec le spécialiste concerné.", "Clarifiez le plan, les risques et le suivi avant de décider."], "Les interventions et les résultats varient selon les personnes. Cette page ne garantit aucun résultat et ne recommande pas une intervention particulière pour vous.", "Demander une évaluation"],
  },
  ru: {
    "second-opinion": ["Второе мнение", "Ещё один взгляд специалиста. Перед вашим решением.", "Пересмотрите диагноз и варианты лечения. Передайте документы и проясните вопросы через оценку специалиста, письменное мнение и видеоконсультацию.", "Новый диагноз, предложенное лечение или оставшиеся вопросы — получите ещё один взгляд специалиста на ваши документы.", ["Понять диагноз", "Рассмотреть варианты лечения", "Задать вопросы специалисту"], ["Передайте диагноз и медицинские документы.", "Специалист изучит дело и при необходимости запросит дополнительные сведения.", "Рассмотрите письменное мнение и варианты, обсуждённые на видеоконсультации."], "Второе мнение не заменяет текущее лечение или экстренную помощь. Медицинские решения основаны на клинической оценке.", "Запросить второе мнение"],
    "medical-tourism": ["Медицинский туризм", "Путь к лечению. План на каждом этапе.", "Рассмотрите варианты лечения в Турции. Начнём с ваших потребностей; лечение и поездка планируются после клинической оценки.", "От потребности в лечении до наблюдения после возвращения — узнайте, что включает каждый этап.", ["Направление лечения и оценка врача", "Предложение, проживание и трансферы", "План последующего наблюдения"], ["Опишите потребности и предпочтения.", "Рассмотрите предложения после оценки врача.", "Уточните подходящее лечение и детали поездки."], "Первичная заявка не предполагает оплаты или бронирования. Возможность лечения, объём и цена определяются после оценки; услуги поездки зависят от предложения.", "Подать заявку на лечение"],
    "medical-aesthetics": ["Эстетическая медицина", "Ваше решение. Подход, подходящий вам.", "Обсудите эстетические цели с врачом. Разберитесь в возможностях, ограничениях и восстановлении до принятия решения.", "Отправная точка — ваши ожидания. Подходящий метод определяется только при индивидуальной оценке.", ["Внешний вид кожи и личные цели", "Показания и возможные риски", "Уход и восстановление"], ["Опишите цели в форме заявки.", "Обсудите варианты и клиническую целесообразность с профильным специалистом.", "Уточните план, риски и наблюдение до принятия решения."], "Процедуры и результаты индивидуальны. Эта страница не гарантирует результат и не рекомендует вам конкретную процедуру.", "Запросить оценку"],
  },
  ar: {
    "second-opinion": ["رأي طبي ثانٍ", "رأي متخصص آخر. قبل قرارك التالي.", "أعد تقييم تشخيصك وخيارات العلاج. شارك مستنداتك ووضّح أسئلتك من خلال مراجعة متخصص ورأي مكتوب واستشارة عبر الفيديو.", "تشخيص جديد أو علاج مقترح أو أسئلة باقية: أضف نظرة متخصص آخر إلى ملفك الحالي.", ["فهم التشخيص", "تقييم خيارات العلاج", "طرح الأسئلة على المتخصص"], ["شارك تشخيصك ومستنداتك الطبية.", "يراجع المتخصص ملفك وقد يطلب معلومات إضافية.", "راجع الرأي المكتوب والخيارات التي نوقشت خلال استشارة الفيديو."], "الرأي الثاني لا يحل محل علاجك الحالي أو الرعاية الطارئة. تعتمد القرارات الطبية على التقييم السريري.", "اطلب رأياً طبياً ثانياً"],
    "medical-tourism": ["السياحة العلاجية", "طريق إلى العلاج. وخطة لكل خطوة.", "استكشف خيارات العلاج في تركيا. نبدأ باحتياجاتك الصحية؛ تتضح خطة العلاج والسفر بعد التقييم السريري.", "من احتياجات العلاج إلى المتابعة بعد العودة، تعرّف على ما تتضمنه كل مرحلة.", ["التخصص وتقييم الطبيب", "العرض والإقامة والتنقلات", "خطة المتابعة"], ["وضّح احتياجاتك الصحية وتفضيلاتك.", "راجع العروض بعد تقييم الطبيب.", "حدّد تفاصيل العلاج المناسب وترتيبات السفر."], "لا يتم دفع أو حجز عند تقديم الطلب الأولي. تُحدّد الملاءمة والنطاق والسعر بعد التقييم؛ وتعتمد خدمات السفر على العرض.", "أنشئ طلب علاج"],
    "medical-aesthetics": ["الطب التجميلي", "قرارك أنت. ونهج يناسبك.", "ناقش أهدافك التجميلية مع طبيب. افهم الخيارات والحدود والتعافي قبل اتخاذ القرار.", "توقعاتك هي نقطة البداية. لا يمكن تحديد النهج المناسب إلا من خلال تقييم فردي.", ["مظهر البشرة والأهداف الشخصية", "الملاءمة والمخاطر المحتملة", "العناية والتعافي"], ["اشرح أهدافك في نموذج طلب العلاج.", "ناقش الخيارات والملاءمة السريرية مع المتخصص المناسب.", "وضّح الخطة والمخاطر والمتابعة قبل القرار."], "تختلف الإجراءات والنتائج من شخص لآخر. لا تضمن هذه الصفحة نتائج ولا توصي بإجراء محدد لك.", "اطلب تقييماً"],
  },
  fa: {
    "second-opinion": ["نظر دوم پزشکی", "دیدگاه متخصصی دیگر. پیش از تصمیم شما.", "تشخیص و گزینه‌های درمان را دوباره بررسی کنید. مدارکتان را به اشتراک بگذارید و با بررسی متخصص، نظر کتبی و مشاوره ویدیویی پرسش‌ها را روشن کنید.", "تشخیص جدید، درمان پیشنهادی یا پرسش‌های باقی‌مانده: دیدگاه متخصص دیگری را به پرونده خود اضافه کنید.", ["درک تشخیص", "بررسی گزینه‌های درمان", "طرح پرسش از متخصص"], ["تشخیص و مدارک پزشکی خود را به اشتراک بگذارید.", "متخصص پرونده را بررسی می‌کند و ممکن است اطلاعات بیشتری بخواهد.", "نظر کتبی و گزینه‌های مطرح‌شده در مشاوره ویدیویی را بررسی کنید."], "نظر دوم جایگزین درمان فعلی یا خدمات اورژانسی نیست. تصمیم پزشکی بر ارزیابی بالینی استوار است.", "درخواست نظر دوم"],
    "medical-tourism": ["گردشگری سلامت", "مسیری برای درمان. برنامه‌ای برای هر گام.", "گزینه‌های درمان در ترکیه را بررسی کنید. از نیازهای سلامت شما آغاز می‌کنیم؛ برنامه درمان و سفر پس از ارزیابی بالینی شکل می‌گیرد.", "از نیاز درمانی تا پیگیری پس از بازگشت، با هر مرحله آشنا شوید.", ["حوزه درمان و ارزیابی پزشک", "پیشنهاد، اقامت و ترانسفر", "برنامه پیگیری"], ["نیازهای سلامت و ترجیحاتتان را بیان کنید.", "پیشنهادها را پس از ارزیابی پزشک بررسی کنید.", "جزئیات درمان مناسب و سفر را روشن کنید."], "در درخواست اولیه پرداخت یا رزرو انجام نمی‌شود. تناسب، دامنه و قیمت پس از ارزیابی مشخص می‌شود؛ خدمات سفر به پیشنهاد بستگی دارد.", "ثبت درخواست درمان"],
    "medical-aesthetics": ["پزشکی زیبایی", "تصمیم شما. رویکردی متناسب با شما.", "اهداف زیبایی خود را با پزشک در میان بگذارید. پیش از تصمیم، گزینه‌ها، محدودیت‌ها و دوره بهبودی را بشناسید.", "انتظارات شما نقطه آغاز است. رویکرد مناسب تنها با ارزیابی فردی مشخص می‌شود.", ["ظاهر پوست و اهداف شخصی", "تناسب و خطرهای احتمالی", "مراقبت و بهبودی"], ["اهدافتان را در فرم درخواست درمان توضیح دهید.", "گزینه‌ها و تناسب بالینی را با متخصص مربوط بررسی کنید.", "پیش از تصمیم، برنامه، خطرها و پیگیری را روشن کنید."], "روش‌ها و نتایج برای هر فرد متفاوت است. این صفحه نتیجه‌ای را تضمین نمی‌کند و روش خاصی را برای شما توصیه نمی‌کند.", "درخواست ارزیابی"],
  },
  az: {
    "second-opinion": ["İkinci rəy", "Qərarınızdan əvvəl, daha bir mütəxəssis rəyi.", "Diaqnozunuzu və müalicə seçimlərini yenidən qiymətləndirin. Sənədlərinizi paylaşın; mütəxəssis qiymətləndirməsi, yazılı rəy və video görüşlə suallarınızı aydınlaşdırın.", "Yeni diaqnoz, təklif edilən müalicə və ya açıq suallar: mövcud sənədlərinizə başqa mütəxəssisin baxışı.", ["Diaqnozu anlamaq", "Müalicə seçimlərini qiymətləndirmək", "Mütəxəssisə sual vermək"], ["Diaqnoz və tibbi sənədlərinizi paylaşın.", "Mütəxəssis sənədləri nəzərdən keçirir və əlavə məlumat istəyə bilər.", "Yazılı rəyi və video görüşdə müzakirə olunan seçimləri qiymətləndirin."], "İkinci rəy mövcud müalicəni və ya təcili tibbi yardımı əvəz etmir. Tibbi qərar klinik qiymətləndirməyə əsaslanır.", "İkinci rəy üçün müraciət et"],
    "medical-tourism": ["Sağlamlıq turizmi", "Müalicə üçün bir yol. Hər addımda bir plan.", "Türkiyədə müalicə seçimlərini qiymətləndirin. Sağlamlıq ehtiyacınızdan başlayaq; müalicə və səfər planı klinik qiymətləndirmədən sonra formalaşır.", "Müalicə ehtiyacından evə qayıtdıqdan sonrakı izləməyə qədər hər mərhələni anlayın.", ["Müalicə sahəsi və həkim qiymətləndirməsi", "Təklif, yaşayış və transfer", "İzləmə planı"], ["Sağlamlıq ehtiyacınızı və seçimlərinizi bildirin.", "Həkim qiymətləndirməsindən sonra təklifləri nəzərdən keçirin.", "Uyğun müalicə və səfər təfərrüatlarını dəqiqləşdirin."], "İlk müraciətdə ödəniş və ya rezervasiya edilmir. Uyğunluq, həcm və qiymət qiymətləndirmədən sonra müəyyən edilir; səfər xidmətləri təklifdən asılıdır.", "Müalicə müraciəti yarat"],
    "medical-aesthetics": ["Tibbi estetika", "Sizin qərarınız. Sizə uyğun yanaşma.", "Estetik hədəflərinizi həkimlə qiymətləndirin. Qərardan əvvəl seçimləri, məhdudiyyətləri və bərpa prosesini anlayın.", "Başlanğıc nöqtəsi sizin gözləntilərinizdir. Uyğun yanaşma fərdi qiymətləndirmə ilə müəyyən edilir.", ["Dərinin görünüşü və şəxsi hədəflər", "Uyğunluq və mümkün risklər", "Qulluq və bərpa"], ["Hədəfinizi müalicə müraciəti formasında təsvir edin.", "Uyğun mütəxəssislə seçimləri və klinik uyğunluğu qiymətləndirin.", "Qərardan əvvəl planı, riskləri və izləməni dəqiqləşdirin."], "Prosedurlar və nəticələr fərdidir. Bu səhifə nəticəyə zəmanət vermir və sizə konkret prosedur tövsiyə etmir.", "Qiymətləndirmə tələb et"],
  },
  bg: {
    "second-opinion": ["Второ мнение", "Още един експертен поглед. Преди решението ви.", "Преразгледайте диагнозата и възможностите за лечение. Споделете документите си и изяснете въпросите чрез оценка от специалист, писмено мнение и видеоконсултация.", "Нова диагноза, предложено лечение или останали въпроси: още един специалист разглежда документите ви.", ["Разбиране на диагнозата", "Оценка на възможностите за лечение", "Въпроси към специалиста"], ["Споделете диагнозата и медицинските документи.", "Специалист преглежда досието и може да поиска допълнителна информация.", "Разгледайте писменото мнение и обсъдените във видеоконсултацията варианти."], "Второто мнение не замества текущото лечение или спешната помощ. Медицинските решения се основават на клинична оценка.", "Заявете второ мнение"],
    "medical-tourism": ["Медицински туризъм", "Път към лечението. План за всяка стъпка.", "Разгледайте възможностите за лечение в Турция. Започваме със здравните ви нужди; лечението и пътуването се планират след клинична оценка.", "От нуждата от лечение до проследяването след завръщането — разберете всеки етап.", ["Област на лечение и лекарска оценка", "Предложение, настаняване и трансфери", "План за проследяване"], ["Опишете здравните си нужди и предпочитания.", "Разгледайте предложенията след лекарската оценка.", "Уточнете подходящото лечение и подробностите за пътуването."], "При първоначалната заявка няма плащане или резервация. Подходящото лечение, обхватът и цената се определят след оценка; пътническите услуги зависят от предложението.", "Заявете лечение"],
    "medical-aesthetics": ["Естетична медицина", "Вашето решение. Подход, съобразен с вас.", "Обсъдете естетичните си цели с лекар. Разберете възможностите, ограниченията и възстановяването, преди да решите.", "Вашите очаквания са отправната точка. Подходящият метод се определя чрез индивидуална оценка.", ["Вид на кожата и лични цели", "Подходящи процедури и възможни рискове", "Грижа и възстановяване"], ["Опишете целите си във формуляра за лечение.", "Обсъдете възможностите и клиничната пригодност с подходящия специалист.", "Изяснете плана, рисковете и проследяването преди решение."], "Процедурите и резултатите са индивидуални. Тази страница не гарантира резултати и не препоръчва конкретна процедура за вас.", "Заявете оценка"],
  },
};

export function moduleCopy(lang: Lang, key: ModuleKey): ModuleText {
  const [name, title, description, focus, topics, steps, note, cta] = rows[lang][key];
  return { name, title, description, focus, topics, steps, note, cta };
}
