import { SURGERY_GUIDES } from "./surgery-guides";
import { withAestheticsJourney } from "./aesthetics-journey";
import { TOURISM_JOURNEY } from "./tourism-journey";
import { GUIDE_DETAILS } from "./guide-depth";
import { text, type LocalText } from "./guide-index";

// [S1+S2+S3] Hasta bilgilendirmesi; kaynak kontrolü 20.09.2026.
// Türkiye istatistikleri AURA ağına ait değildir. Kurum örnekleri iş ortaklığı değildir.
export type Guide = {
  intro: LocalText;
  navigation?: { label: LocalText; href: string }[];
  sections: { title: LocalText; body: LocalText; items?: LocalText[]; links?: { label: LocalText; href: string }[] }[];
  sources: { name: string; url: string }[];
  stats?: { value: string; label: LocalText; note: LocalText }[];
};
const cleveland = { name: "Cleveland Clinic — Virtual Second Opinions", url: "https://my.clevelandclinic.org/online-services/virtual-second-opinions" };
const stanford = { name: "Stanford Health Care — Online Second Opinion", url: "https://stanfordhealthcare.org/second-opinion/overview.html" };
const health = { name: "HealthTürkiye — Türkiye Health System", url: "https://healthturkiye.gov.tr/turkiye-health-system" };
const heal = { name: "Heal in Türkiye — Ticaret Bakanlığı / HİB", url: "https://www.healinturkiye.gov.tr/" };
const ushas = { name: "USHAŞ — Sağlık Turizmi Verileri (TÜİK)", url: "https://www.ushas.gov.tr/saglik-turizmi-verileri/" };
const authorized = { name: "Sağlık Bakanlığı — Yetkili Sağlık Tesisleri, 20.08.2026", url: "https://shgmturizmdb.saglik.gov.tr/TR-76664/yetkili-saglik-tesisleri.html" };
const hospitals = { name: "Sağlık Bakanlığı — Yetkili Hastaneler Listesi (541 kayıt)", url: "https://dosyamerkez.saglik.gov.tr/Eklenti/56170/0/hastanelerpdf.pdf" };
const yearbook = { name: "Sağlık İstatistikleri Yıllığı 2024 — PDF s.159 ve s.258", url: "https://dosyamerkez.saglik.gov.tr/Eklenti/52859/0/siy2024tr31122025pdf.pdf" };
const before = { name: "NHS — Before you have a cosmetic procedure", url: "https://www.nhs.uk/tests-and-treatments/cosmetic-procedures/advice/before-you-have-a-cosmetic-procedure/" };
const choosing = { name: "NHS — Choosing who will do your cosmetic procedure", url: "https://www.nhs.uk/tests-and-treatments/cosmetic-procedures/advice/choosing-who-will-do-your-procedure/" };
const surgery = { name: "NHS — Cosmetic surgery", url: "https://www.nhs.uk/tests-and-treatments/cosmetic-procedures/cosmetic-surgery/" };
const BASE_GUIDES: Record<string, Guide> = {
  ...SURGERY_GUIDES,
  "what-is-a-second-opinion": {
    intro: text("İkinci Görüş, mevcut tanı veya tedavi planınızın başka bir doktor tarafından değerlendirilmesidir. Amaç, seçenekleri daha iyi anlamanıza ve kendi doktorunuzla daha bilinçli karar vermenize yardımcı olmaktır.", "A second opinion is another clinician’s assessment of an existing diagnosis or treatment plan. It can help you understand your options and make a more informed decision with your treating clinician."),
    sections: [
      { title: text("Ne zaman düşünülebilir?", "When might it help?"), body: text("Önemli bir tanı aldığınızda, ameliyat önerildiğinde veya farklı tedavi seçenekleri arasında kaldığınızda ikinci bir değerlendirme isteyebilirsiniz. Bu talep, mevcut doktorunuza güvenmediğiniz anlamına gelmez.", "You may consider another assessment after a significant diagnosis, a recommendation for surgery or when facing different treatment options. Asking does not mean you distrust your current clinician."), items: [text("Tanınızın dayanağını ve belirsizlikleri anlamak.", "Understand the evidence and uncertainties behind your diagnosis."), text("Önerilen tedavinin alternatiflerini konuşmak.", "Discuss alternatives to the proposed treatment."), text("Beklenen yararları, riskleri ve takip ihtiyacını netleştirmek.", "Clarify potential benefits, risks and follow-up needs.")] },
      { title: text("Görüş neyi değiştirebilir?", "What can an opinion change?"), body: text("Uzman, mevcut yaklaşımı destekleyebilir, başka seçenekler tartışabilir veya ek belge ve muayene isteyebilir. Farklı bir sonuç çıkacağı garanti edilmez. Görüşler ayrışırsa her iki yaklaşımın gerekçelerini tedavinizi yürüten doktorla değerlendirin.", "The specialist may support the current approach, discuss alternatives or request additional records or an examination. A different conclusion is not guaranteed. If opinions differ, discuss the reasoning with your treating clinician.") },
      { title: text("Uzaktan değerlendirmenin sınırları", "Limits of a remote assessment"), body: text("Dosya üzerinden görüş, fizik muayenenin ve gerekli tetkiklerin yerini her durumda tutmaz. Eksik veya güncel olmayan kayıtlar değerlendirmeyi sınırlayabilir. İkinci Görüş beklerken ilaçlarınızı veya mevcut tedavinizi kendiniz değiştirmeyin; acil belirtilerde yerel acil sağlık hizmetine başvurun.", "A records-based review cannot always replace a physical examination or necessary tests. Missing or outdated records can limit the assessment. Do not change medication or treatment while waiting without discussing it with your clinician; seek local emergency care for urgent symptoms.") },
    ], sources: [cleveland, stanford],
  },
  "how-it-works": {
    intro: text("İyi bir İkinci Görüş, açık bir soruyla ve düzenli bir tıbbi dosyayla başlar. Başvuru, klinik değerlendirme ve sonraki adımlar birbirinden ayrı aşamalardır.", "A useful second opinion starts with a clear question and an organised medical record. Applying, receiving a clinical assessment and deciding on next steps are separate stages."),
    sections: [
      { title: text("1. Sorunuzu ve dosyanızı hazırlayın", "1. Prepare your question and records"), body: text("Hangi karar hakkında görüş istediğinizi bir veya iki cümleyle anlatın. Şikâyetlerin başlangıcını, konulan tanıyı ve önerilen tedaviyi tarih sırasıyla özetleyin. Kayıtların okunaklı ve size ait olduğundan emin olun.", "Explain the decision you need help with in one or two sentences. Summarise symptoms, diagnosis and proposed treatment in date order. Ensure your records are legible and belong to you."), items: [text("Epikriz, uzman raporları ve ilgili tetkik sonuçları.", "Discharge summaries, specialist reports and relevant test results."), text("Gerekliyse görüntüleme raporu ile orijinal görüntüler ve patoloji raporu.", "Imaging reports and original images, and pathology reports where relevant."), text("Kullandığınız ilaçlar, alerjiler ve geçirilmiş işlemler.", "Current medicines, allergies and previous procedures.")] },
      { title: text("2. Başvuru ve uzman değerlendirmesi", "2. Application and specialist review"), body: text("AURA başvurusunda durumunuzu ve görüş talebinizi iletirsiniz. Değerlendirme için gerekli bilgiler ve uygun uzmanlık alanı netleştirilir. Eksik belgeler istenebilir. Süre, ücret ve görüşün kapsamı başvuruya göre ayrıca açıklanmalıdır; bu rehber sabit bir teslim süresi veya sonuç vaat etmez.", "In your AURA application, describe your situation and the opinion you are seeking. The information needed and relevant specialty are clarified, and missing records may be requested. Timing, fees and scope must be explained for your application; this guide does not promise a fixed turnaround or outcome.") },
      { title: text("3. Görüşü tedavi planınıza taşıyın", "3. Discuss the opinion with your clinician"), body: text("Görüşün hangi belgelere dayandığını, belirsiz kalan noktaları ve önerilen sonraki adımları sorun. Raporu kendi doktorunuzla paylaşın. Ek muayene, tetkik veya tedavi değişikliği gerekip gerekmediğine klinik değerlendirmeyle karar verilir.", "Ask which records support the opinion, what remains uncertain and what the next steps are. Share the report with your treating clinician. Further examination, testing or changes to treatment require clinical assessment.") },
    ], sources: [cleveland, stanford],
  },
  "global-examples": {
    intro: text("Uluslararası İkinci Görüş programları farklı erişim modelleri sunar. Aşağıdaki örnekler hizmetin nasıl yapılandırılabildiğini anlatır; bir sıralama veya AURA ile ortaklık beyanı değildir.", "International second-opinion programmes use different access models. These examples illustrate how services can be organised; they are not a ranking or a statement of partnership with AURA."),
    sections: [
      { title: text("Cleveland Clinic", "Cleveland Clinic"), body: text("Virtual Second Opinions programı tıbbi kayıtların toplanması, uzman eşleştirmesi ve yazılı değerlendirme adımlarını açıklar. Bazı konumlarda rapora ek sanal görüşme seçeneği bulunur. Ülke ve bölgeye göre uygunluk değişebilir; güncel koşullar kurumun kendi sayfasından kontrol edilmelidir.", "Its Virtual Second Opinions programme describes record collection, specialist matching and a written assessment. An additional virtual visit is available in some locations. Eligibility varies by location; check the institution’s current terms directly.") },
      { title: text("Stanford Health Care", "Stanford Health Care"), body: text("Online Second Opinion programı mevcut tanı ve tedavi sorularının uzman tarafından uzaktan incelenmesine odaklanır. Başvurunun kabulü ve değerlendirilebilen durumlar programın koşullarına bağlıdır. Çevrim içi dosya incelemesi ile yüz yüze bakımın kapsamı aynı değildir.", "Its Online Second Opinion programme focuses on remote specialist review of existing diagnoses and treatment questions. Acceptance and eligible conditions depend on programme requirements. An online record review and in-person care have different scopes.") },
      { title: text("Programları nasıl karşılaştırabilirsiniz?", "How can you compare programmes?"), body: text("Yalnızca kurum adına bakmayın. Görüşü verecek uzmanın alanını, istenen kayıtları, rapor kapsamını ve sonradan soru sorma imkânını karşılaştırın. Fiyat, geri ödeme, ülkenizde erişim ve tercüme ihtiyacını başvurmadan önce öğrenin. Başka bir kurumun başarı oranı veya teslim süresi AURA için geçerli kabul edilemez.", "Compare the reviewing specialist’s field, required records, report scope and opportunity for follow-up questions. Check pricing, reimbursement, access in your country and translation needs before applying. Another programme’s outcomes or turnaround times do not describe AURA’s service.") },
    ], sources: [cleveland, stanford],
  },
  "healthcare-in-turkiye": {
    intro: text("Sağlık Turizmi, sağlık hizmeti almak amacıyla başka bir ülkeye seyahat edilmesini ifade eder. Türkiye’de kamu, üniversite ve özel sağlık kuruluşları farklı uzmanlık alanlarında hizmet verir.", "Medical tourism means travelling to another country to receive healthcare. Public, university and private providers in Türkiye offer care across different specialties."),
    sections: [
      { title: text("Hangi alanlar yer alır?", "Which areas are included?"), body: text("Uluslararası hasta hizmetleri onkoloji, ortopedi, kardiyoloji, göz hastalıkları, üreme sağlığı, diş tedavileri ve estetik uygulamalar gibi farklı alanları kapsayabilir. Her işlemin uygunluğu kişiye ve kuruluşun yetkinliğine bağlıdır. Bir branşın bu rehberde yer alması, AURA’da her işlem için hizmet garantisi anlamına gelmez.", "International patient care can include oncology, orthopaedics, cardiology, eye care, reproductive health, dentistry and aesthetic procedures. Suitability depends on the person and the provider’s capabilities. Listing a specialty here does not guarantee that every procedure is available through AURA.") },
      { title: text("HealthTürkiye ve Heal in Türkiye", "HealthTürkiye and Heal in Türkiye"), body: text("HealthTürkiye, Sağlık Bakanlığı markası altında sağlık sistemi, kuruluşlar ve hasta yolculuğu hakkında bilgi sunar. Heal in Türkiye, Ticaret Bakanlığı ve Hizmet İhracatçıları Birliğiyle ilişkili tanıtım portalıdır; tedaviler ve hizmet sağlayıcıları hakkında içerik içerir. İki portalın farklı tarihli sayaçları aynı kapsamı göstermeyebilir.", "HealthTürkiye provides information about the healthcare system, providers and the patient journey under the Ministry of Health brand. Heal in Türkiye is a promotional portal associated with the Ministry of Trade and the Service Exporters’ Association, covering treatments and providers. Counters from different periods may not measure the same things.") },
      { title: text("Kurum seçerken neyi doğrulamalısınız?", "What should you verify?"), body: text("Kuruluşun Sağlık Turizmi yetki belgesini Bakanlığın güncel listesinden kontrol edin. Doktorun uzmanlığı, işlemin yapılacağı adres, anestezi ve acil durum imkânları, takip sorumluluğu ve teklif kapsamını yazılı olarak öğrenin. Akreditasyon varsa kuruluş adı, kapsamı ve geçerlilik tarihini ayrıca doğrulayın.", "Check the provider’s health-tourism authorisation against the Ministry’s current list. Ask for the clinician’s specialty, treatment location, anaesthesia and emergency arrangements, follow-up responsibility and proposal scope in writing. Where accreditation is claimed, check the organisation, scope and validity separately.") },
    ], sources: [health, heal, authorized],
  },
  "facts-and-figures": {
    intro: text("Bu rakamlar Türkiye geneline aittir; AURA’nın anlaşmalı kurum veya doktor sayısını göstermez. Her göstergenin dönemi ve tanımı ayrı verilmiştir. Kaynaklar 20 Eylül 2026’da kontrol edilmiştir.", "These figures describe Türkiye as a whole, not AURA’s partner institutions or clinicians. Each indicator has its own period and definition. Sources were checked on 20 September 2026."),
    stats: [
      { value: "1.398.580", label: text("Sağlık amaçlı ziyaretçi", "Visitors for healthcare"), note: text("2025 tam yıl · USHAŞ / TÜİK", "Full year 2025 · USHAŞ / TÜİK") },
      { value: "541", label: text("Yetkili hastane kaydı", "Authorised hospital entries"), note: text("20.08.2026 tarihli Bakanlık listesi", "Ministry list dated 20 August 2026") },
      { value: "1.562", label: text("Türkiye’de toplam hastane", "Total hospitals in Türkiye"), note: text("2024 · tüm sektörler", "2024 · all sectors") },
      { value: "221.133", label: text("Türkiye’de toplam doktor", "Total physicians in Türkiye"), note: text("2024 · diş doktorları ayrı kategoridir", "2024 · dentists are a separate category") },
    ],
    sections: [
      { title: text("Yıllık ziyaretçi sayıları", "Annual healthcare visitors"), body: text("USHAŞ’ın TÜİK kaynaklı serisinde sağlık hizmeti almak için gelen kişi sayısı 2023’te 1.538.643, 2024’te 1.506.442 ve 2025’te 1.398.580’dir. 2025 Sağlık Turizmi geliri 3.022.452 bin ABD dolarıdır (yaklaşık 3,02 milyar dolar). Ziyaretçi sayısı işlem veya ameliyat sayısı değildir; kısmi yıl verileri bu tam yıl serisine eklenmemiştir.", "USHAŞ’s TÜİK-based series reports 1,538,643 healthcare visitors in 2023, 1,506,442 in 2024 and 1,398,580 in 2025. Health-tourism revenue in 2025 was USD 3,022,452 thousand (about USD 3.02 billion). Visitor numbers are not procedure or surgery counts. Partial-year figures are excluded from this annual series.") },
      { title: text("541 sayısı neyi ifade ediyor?", "What does 541 represent?"), body: text("Bakanlığın 20 Ağustos 2026 güncellemesi altında yayımlanan Yetkili Hastaneler PDF’sinde sıra numaraları 1’den 541’e uzanır. Bu, o listedeki hastane kayıtlarının sayımıdır. Tıp merkezleri, muayenehaneler ve diğer sağlık tesisleri ayrı listelerde bulunur. Bu sayı tüm sağlık tesislerini veya akredite hastaneleri temsil etmez; güncel durum başvuru öncesi tekrar kontrol edilmelidir.", "The Authorised Hospitals PDF linked from the Ministry’s 20 August 2026 update contains entries numbered 1 through 541. This is a count of hospital entries in that list. Medical centres, practices and other facilities have separate lists. It is not a count of all facilities or accredited hospitals; recheck current status before applying.") },
      { title: text("Hastane ve doktor kapasitesi", "Hospital and physician capacity"), body: text("Sağlık İstatistikleri Yıllığı 2024’te tüm sektörler için 1.562 hastane ve 221.133 doktor bildirilir. Hastane toplamı 941 Bakanlık, 69 üniversite ve 552 özel hastaneden oluşur. Doktor sayısı Sağlık Turizmi için özel olarak yetkilendirilmiş veya AURA’ya kayıtlı doktor sayısı değildir. Diş doktorları yıllıkta ayrıca sayılır.", "The 2024 Health Statistics Yearbook reports 1,562 hospitals and 221,133 physicians across all sectors. The hospital total comprises 941 Ministry, 69 university and 552 private hospitals. The physician total is not a count of health-tourism-authorised doctors or AURA members. Dentists are counted separately in the yearbook.") },
      { title: text("Yetki belgesi ve akreditasyon farklıdır", "Authorisation and accreditation are different"), body: text("Sağlık Turizmi yetki belgesi bir faaliyet yetkisidir. Akreditasyon ise belirli standartların değerlendirilmesiyle ilgilidir. Bakanlığın 11 Haziran 2026 duyurusu, ilgili tesisler için 31 Aralık 2026’ya kadar TÜSKA akreditasyonu veya sertifikasyon yükümlülüğünü açıklar. Geçiş süresi, listedeki bütün hastanelerin bugün akredite olduğu anlamına gelmez.", "Health-tourism authorisation permits an activity. Accreditation concerns assessment against particular standards. The Ministry’s 11 June 2026 notice describes TÜSKA accreditation or certification obligations for relevant facilities by 31 December 2026. A transition deadline does not mean that every listed hospital is already accredited.") },
    ], sources: [ushas, hospitals, authorized, yearbook, { name: "Sağlık Bakanlığı — Sertifikasyon Kriter Seti, 11.06.2026", url: "https://shgmturizmdb.saglik.gov.tr/TR-118129/saglik-turizmi-sertifikasyon-kriter-seti.html" }, health, heal],
  },
  "planning-your-journey": {
    intro: text("Tedavi seyahati yalnızca uçuş ve konaklamadan oluşmaz. Klinik değerlendirme, yazılı teklif ve eve döndükten sonraki bakım birlikte planlanmalıdır.", "Travelling for treatment involves more than flights and accommodation. Clinical assessment, a written proposal and care after returning home need to be planned together."),
    sections: [
      { title: text("Seyahatten önce", "Before travelling"), body: text("Tıbbi kayıtlarınızı ve beklentilerinizi paylaşın. Kurum ve doktor bilgilerini doğrulayın; yüz yüze değerlendirmede planın değişebileceğini hesaba katın. Teklifte tedavi, tetkik, anestezi, konaklama, tercüman ve transfer kalemlerinden hangilerinin bulunduğunu sorun.", "Share your medical records and expectations. Verify the provider and clinician, and allow for the plan to change after an in-person assessment. Ask which treatment, tests, anaesthesia, accommodation, interpreting and transfer costs the proposal includes.") },
      { title: text("Tedavi ve iyileşme döneminde", "During treatment and recovery"), body: text("İşlem öncesi doktorla alternatifleri, kişisel riskleri ve beklenen iyileşmeyi konuşun. Anladığınız dilde açıklama ve onam isteyin. Kontrol randevularını, refakatçi ihtiyacını ve uçuşa uygunluk değerlendirmesini planınıza ekleyin. Turistik etkinlikleri klinik önerilere göre düzenleyin.", "Discuss alternatives, personal risks and expected recovery with your clinician. Request explanations and consent information in a language you understand. Include check-ups, any companion needs and assessment of fitness to fly. Plan tourism activities around clinical advice.") },
      { title: text("Eve döndükten sonra", "After returning home"), body: text("Epikriz, yapılan işlem, kullanılan ürün veya implant bilgileri ve kontrol planını yazılı alın. Bir sorun olduğunda kimi arayacağınızı, yerel muayenenin nasıl sağlanacağını ve ek maliyetlerden kimin sorumlu olacağını öğrenin. Sigortanın kapsamı, istisnaları ve geçerlilik süresi poliçeden kontrol edilmelidir.", "Obtain written records of your treatment, products or implants used, and follow-up plan. Clarify whom to contact, how local assessment will be arranged and responsibility for additional costs. Check insurance coverage, exclusions and validity in the policy.") },
      { title: text("AURA başvurusu", "Applying through AURA"), body: text("Sağlık Turizmi başvurusu ihtiyaçlarınızı iletmek için başlangıç adımıdır. Başvuru tek başına ödeme, rezervasyon veya kesin tedavi taahhüdü oluşturmaz. Kişisel plan ve teklif, değerlendirme sonrasında netleştirilir.", "A medical-tourism enquiry is the starting point for sharing your needs. Applying alone does not create a payment, reservation or confirmed treatment commitment. Your personal plan and proposal are clarified after assessment.") },
    ], sources: [health, heal, { name: "NHS — Cosmetic surgery abroad", url: "https://www.nhs.uk/tests-and-treatments/cosmetic-procedures/advice/cosmetic-surgery-abroad/" }],
  },
  "aesthetic-surgery": {
    intro: text("Estetik cerrahi, görünümle ilgili hedefler için yapılan cerrahi işlemleri kapsar. AURA’nın estetik başlığı cerrahi ve cerrahi olmayan alanları bir araya getirir; bunlar aynı işlem veya aynı uzmanlık değildir.", "Aesthetic surgery covers operations intended to address appearance-related goals. AURA’s aesthetics section brings together surgical and non-surgical fields; they are not the same procedures or specialties."),
    sections: [
      { title: text("Yüz ve burun cerrahisi", "Face and nose surgery"), body: text("Rinoplasti, göz kapağı cerrahisi, yüz ve boyun germe, kulak şekillendirme bu grupta değerlendirilebilir. Görünüm hedefi ile solunum veya görme gibi işlevsel sorunlar ayrı konuşulmalıdır. Yüz oranları ve beklentiler, muayenede birlikte değerlendirilir.", "This group can include rhinoplasty, eyelid surgery, face and neck lifts and ear reshaping. Appearance goals and functional concerns such as breathing or vision should be discussed separately. Facial proportions and expectations are assessed during consultation.") },
      { title: text("Meme cerrahisi", "Breast surgery"), body: text("Büyütme, küçültme ve dikleştirme farklı amaçlara yönelik işlemlerdir. İmplant düşünülüyorsa ürün bilgileri, kontroller ve gelecekte ek işlem ihtimali görüşülmelidir. İzlerin yeri, duyu değişikliği ve kişisel beklentiler kararın parçasıdır.", "Augmentation, reduction and uplift address different goals. If considering implants, discuss product information, follow-up and the possibility of further procedures. Scarring, sensation changes and personal expectations are part of the decision.") },
      { title: text("Vücut şekillendirme", "Body contouring"), body: text("Liposuction, karın germe ve kol veya uyluk germe gibi işlemler farklı doku ve bölgeleri hedefler. Cerrahi bir kilo yönetimi planıyla eşdeğer değildir. Birden fazla işlemin birlikte yapılması kişisel risk ve iyileşme yükü açısından doktor tarafından değerlendirilmelidir.", "Liposuction, abdominoplasty and arm or thigh lifts address different tissues and areas. Surgery is not equivalent to a weight-management plan. Combining procedures requires assessment of individual risk and recovery demands.") },
      { title: text("Kararda yer alması gerekenler", "What belongs in the decision"), body: text("Kanama, enfeksiyon, anesteziyle ilişkili sorunlar, iz ve beklentinin karşılanmaması gibi riskleri sorun. İşlem yapmama seçeneğini, alternatifleri, işe dönüşü ve takip sorumluluğunu konuşun. Uygunluk yalnız fotoğraf veya çevrim içi form üzerinden kesinleştirilemez.", "Ask about bleeding, infection, anaesthetic problems, scarring and an unsatisfactory result. Discuss alternatives including no treatment, return to work and follow-up responsibility. Suitability cannot be confirmed from a photograph or online form alone.") },
    ], sources: [surgery, before],
  },
  "dental-aesthetics": {
    intro: text("Diş estetiğinde görünüm kadar dişlerin, diş etlerinin ve kapanışın sağlığı da önemlidir. Plan, diş doktoru muayenesi ve gerektiğinde görüntüleme sonrasında oluşturulur.", "Dental aesthetics considers the health of teeth, gums and bite as well as appearance. Planning follows a dental examination and imaging where needed."),
    sections: [
      { title: text("Beyazlatma ve yüzey uygulamaları", "Whitening and surface treatments"), body: text("Beyazlatma diş rengini değiştirmeyi amaçlar. Bonding ve lamina kaplamalar şekil veya görünüm için farklı seçeneklerdir. Her diş yapısı ve her renklenme aynı yönteme uygun değildir; hassasiyet ve bakım ihtiyacını sorun.", "Whitening aims to change tooth colour. Bonding and veneers offer different ways to alter shape or appearance. Not every tooth or type of staining suits the same approach; ask about sensitivity and maintenance.") },
      { title: text("Kaplama, implant ve ortodonti", "Crowns, implants and orthodontics"), body: text("Kronlar, eksik dişlerin implant veya köprüyle tamamlanması ve ortodonti farklı klinik ihtiyaçlara yanıt verir. İmplant cerrahi bir tedavidir; yalnızca gülüş görünümü üzerinden seçilmez. Ortodonti ise dişlerin konumunu ve kapanışı değerlendirir.", "Crowns, implants or bridges for missing teeth, and orthodontics address different clinical needs. Implants involve surgery and are not selected solely for smile appearance. Orthodontics considers tooth position and bite.") },
      { title: text("Diş dokusunu ve uzun vadeyi konuşun", "Discuss tooth preservation and long-term care"), body: text("İşlemde sağlam diş dokusu kaldırılıp kaldırılmayacağını, geri dönüş olup olmadığını, alternatifleri ve gelecekte yenileme gereksinimini sorun. İyileşme, ağız bakımı ve kontroller seyahat sonrasına da uzanabilir. Birden çok ziyaret gerekip gerekmediğini teklif aşamasında öğrenin.", "Ask whether healthy tooth tissue will be removed, whether changes are reversible, what alternatives exist and whether replacements may be needed. Healing, oral care and check-ups can extend beyond the trip. Clarify the need for multiple visits when discussing the proposal.") },
    ], sources: [{ name: "NHS — Dental treatments", url: "https://www.nhs.uk/live-well/healthy-teeth-and-gums/dental-treatments/" }, choosing],
  },
  "hair-transplant": {
    intro: text("Saç ekimi, saç köklerinin donör bölgeden seyrek veya saçsız alana taşınmasıdır. Önce saç dökülmesinin nedeni ve donör alanın durumu değerlendirilmelidir.", "Hair transplantation moves hair follicles from a donor area to an area with thinning or absent hair. The cause of hair loss and the condition of the donor area need assessment first."),
    sections: [
      { title: text("Kimler için değerlendirilir?", "Who may be assessed?"), body: text("Her saç dökülmesi ekime uygun değildir. Dökülmenin türü, ilerleyişi, saçlı derinin durumu ve beklentiler birlikte ele alınır. İlaç veya başka yaklaşımlar da değerlendirmeye dahil olabilir. Donör alan sınırlıdır; greft sayısı tek başına kalite ölçütü değildir.", "Not all hair loss is suitable for transplantation. Its type and progression, scalp condition and expectations are assessed together. Medicines or other approaches may also be considered. Donor supply is limited; graft count alone is not a measure of quality.") },
      { title: text("FUE ve FUT neyi anlatır?", "What do FUE and FUT describe?"), body: text("FUE’de kökler tek tek, FUT’ta ise saçlı deri şeridi üzerinden elde edilir. Yöntem seçimi kişisel özelliklere ve cerrahın değerlendirmesine bağlıdır. Kullanılan ticari ad, tek başına farklı bir klinik sonuç veya üstünlük kanıtı değildir.", "FUE obtains follicles individually, while FUT obtains them from a strip of scalp. The choice depends on individual characteristics and the surgeon’s assessment. A commercial label alone does not demonstrate a different outcome or superiority.") },
      { title: text("İyileşme ve takip", "Recovery and follow-up"), body: text("Şişlik, hassasiyet ve kabuklanma görülebilir; enfeksiyon, iz ve greftlerin tutmaması gibi riskler vardır. Sonuç hemen oluşmaz ve çevredeki saçlarda dökülme devam edebilir. İşlemi kimin yaptığı, bakım talimatları ve beklenmeyen belirtilerde ulaşılacak ekip önceden netleşmelidir.", "Swelling, tenderness and scabbing can occur; risks include infection, scarring and graft failure. Results take time and surrounding hair may continue to thin. Clarify who performs the procedure, aftercare instructions and whom to contact about unexpected symptoms.") },
    ], sources: [{ name: "NHS — Hair transplant", url: "https://www.nhs.uk/tests-and-treatments/cosmetic-procedures/cosmetic-surgery/hair-transplant/" }],
  },
  "injectable-treatments": {
    intro: text("Botulinum toksini ile dermal dolgu farklı etki mekanizmalarına sahiptir. İkisinin de uygunluğu tıbbi öykü, muayene ve kullanılan ürüne göre değerlendirilir.", "Botulinum toxin and dermal fillers work differently. Suitability for either depends on medical history, examination and the product being used."),
    sections: [
      { title: text("Botulinum toksini", "Botulinum toxin"), body: text("Belirli kasların aktivitesini geçici olarak azaltmayı amaçlayan bir uygulamadır. Her kırışıklık veya görünüm hedefi için uygun değildir. İlaçlar, geçirilmiş uygulamalar ve hastalıklar değerlendirmede açıklanmalıdır; doz ve uygulama alanını yetkili klinisyen belirler.", "This treatment aims to temporarily reduce activity in particular muscles. It is not suitable for every wrinkle or appearance goal. Disclose medicines, previous treatments and medical conditions; an authorised clinician determines dose and treatment area.") },
      { title: text("Dermal dolgu", "Dermal fillers"), body: text("Dolgular seçilen bölgede hacim veya kontur değişikliği için kullanılır. Ürün, uygulama yeri ve uygulayıcının eğitimi önemlidir. Morarma ve şişlik yanında enfeksiyon, damar tıkanıklığı ve nadiren görme kaybı gibi ciddi komplikasyonlar gelişebilir.", "Fillers are used to change volume or contour in selected areas. The product, injection site and practitioner’s training matter. Alongside bruising and swelling, serious complications can include infection, vascular blockage and, rarely, loss of vision.") },
      { title: text("Uygulamadan önce sorulacaklar", "Questions before treatment"), body: text("Ürünün adını ve kaynağını, işlemi kimin yapacağını, beklenen etki süresini, alternatifleri ve komplikasyon planını sorun. Cerrahi olmaması risksiz olduğu anlamına gelmez. Uygulama sonrası ani görme değişikliği, şiddetli ağrı veya solunum güçlüğü acil değerlendirme gerektirir.", "Ask for the product name and source, who will perform treatment, expected duration, alternatives and the complication plan. Non-surgical does not mean risk-free. Sudden visual changes, severe pain or breathing difficulty after treatment require urgent assessment.") },
    ], sources: [choosing, before, { name: "FDA — Dermal Fillers", url: "https://www.fda.gov/medical-devices/aesthetic-cosmetic-devices/dermal-fillers-soft-tissue-fillers" }],
  },
  "skin-and-laser": {
    intro: text("Cilt uygulamaları tek bir işlemden oluşmaz. Hedef, cilt tipi, mevcut hastalıklar ve kullanılan ilaçlar yöntemin seçiminde önem taşır.", "Skin treatments are not a single procedure. Goals, skin type, medical conditions and medicines matter when choosing an approach."),
    sections: [
      { title: text("Peeling ve cilt yenileme", "Peels and resurfacing"), body: text("Kimyasal peeling ve farklı cilt yenileme yöntemleri yüzey, doku veya renk görünümü için değerlendirilebilir. Uygulamanın derinliği arttıkça iyileşme ihtiyacı da değişir. Aktif enfeksiyon, iz öyküsü ve önceki işlemler doktora bildirilmelidir.", "Chemical peels and resurfacing approaches may be considered for skin surface, texture or colour. Recovery needs vary with treatment depth. Tell your clinician about active infections, scarring history and previous procedures.") },
      { title: text("Lazer, ışık ve enerji temelli yöntemler", "Laser, light and energy-based approaches"), body: text("Lazer, IPL ve radyofrekans gibi yöntemler farklı hedeflere yöneliktir; birbirinin yerine kullanılamaz. Cilt yenileme, bazı lekeler, izler veya istenmeyen kıllar için yapılan değerlendirmeler farklı olabilir. Şüpheli bir cilt lezyonu kozmetik işlemden önce tıbben incelenmelidir.", "Laser, IPL and radiofrequency target different concerns and are not interchangeable. Assessment for resurfacing, some pigmentation concerns, scars or unwanted hair may differ. A suspicious skin lesion requires medical assessment before cosmetic treatment.") },
      { title: text("Cilt tipi, risk ve bakım", "Skin type, risk and aftercare"), body: text("Yanık, enfeksiyon, iz ve açık veya koyu renk değişiklikleri olası risklerdendir. Risk, cilt tonu ve kullanılan yönteme göre değişir. Seans sayısı, iyileşme, güneşten korunma ve ürün kullanımı kişisel planın parçası olmalıdır; tek seansta kalıcı sonuç garantisi verilmez.", "Possible risks include burns, infection, scars and lighter or darker pigmentation. Risk varies with skin tone and the method used. Session numbers, healing, sun protection and product use belong in an individual plan; a permanent result from one session cannot be guaranteed.") },
    ], sources: [{ name: "ASPS — Skin rejuvenation: risks and safety", url: "https://www.plasticsurgery.org/cosmetic-procedures/skin-rejuvenation-and-resurfacing/safety" }, { name: "Mayo Clinic — Laser resurfacing", url: "https://www.mayoclinic.org/tests-procedures/laser-resurfacing/about/pac-20385114" }],
  },
  "before-you-decide": {
    intro: text("Estetik bir işlem kişisel bir karardır. Başlangıç noktası bir paket seçmek değil, ne istediğinizi ve hangi riskleri kabul edebileceğinizi anlamaktır.", "An aesthetic procedure is a personal decision. Start by understanding what you want and which risks you are willing to accept before selecting a package."),
    sections: [
      { title: text("Beklentinizi açıkça anlatın", "Explain your expectations"), body: text("Neyi değiştirmek istediğinizi ve sonucun günlük yaşamınızda ne anlama geldiğini konuşun. Öncesi-sonrası fotoğrafları sizin sonucunuzu garanti etmez. Kararsızsanız düşünmek için zaman ayırın; işlem yaptırmamak da bir seçenektir.", "Discuss what you want to change and what the result would mean in daily life. Before-and-after photographs cannot guarantee your result. Take time if you are uncertain; choosing no procedure is also an option.") },
      { title: text("Uzmanlığı ve işlem yerini doğrulayın", "Verify expertise and the setting"), body: text("İşlemi yapacak kişinin kimliğini, uzmanlığını ve bu işlemdeki deneyimini öğrenin. Kuruluşun yetkisini, acil durumda kullanılacak imkânları ve komplikasyon halinde sorumlulukları kontrol edin. Sadece sosyal medya görünürlüğü veya indirim üzerinden karar vermeyin.", "Find out the practitioner’s identity, specialty and experience in your procedure. Check the facility’s authorisation, emergency arrangements and responsibility for complications. Do not decide solely on social-media visibility or a discount.") },
      { title: text("Yazılı planınızı tamamlayın", "Complete your written plan"), body: text("Alternatifler, kişisel riskler, toplam maliyet, iyileşme süresi ve kontroller açık olmalıdır. Seyahat ediyorsanız eve dönüş sonrası bakım ve tekrar ziyaret ihtiyacını da konuşun. Bu rehber genel bilgilendirmedir; kişisel tanı veya işlem önerisi yerine geçmez.", "Your plan should explain alternatives, individual risks, total costs, recovery and check-ups. If travelling, discuss care at home and possible repeat visits. This guide is general information, not a personal diagnosis or procedure recommendation.") },
    ], sources: [before, choosing],
  },
};

// Yeni ayrıntılar konu akışına yerleştirilir; seyahat rehberi hazırlıktan takibe ilerler.
const SECTION_ORDER: Record<string, number[]> = {
  "what-is-a-second-opinion": [0,3,1,4,2,5], "how-it-works": [0,3,4,1,2,5],
  "global-examples": [0,1,3,2,4,5], "healthcare-in-turkiye": [3,0,4,1],
  "planning-your-journey": [0,4,5,1,2,6,3], "aesthetic-surgery": [0,1,2,4,3,5,6],
  "dental-aesthetics": [3,0,1,2,4,5], "hair-transplant": [0,3,1,4,2,5],
  "injectable-treatments": [3,0,1,4,2,5], "skin-and-laser": [3,0,1,4,2,5],
  "before-you-decide": [0,3,1,4,2,5],
};
export const GUIDES: Record<string, Guide> = Object.fromEntries(Object.entries(BASE_GUIDES).map(([slug, guide]) => {
  if (slug === "planning-your-journey") return [slug, TOURISM_JOURNEY];
  const sections = [...guide.sections, ...(GUIDE_DETAILS[slug] ?? [])];
  if (slug === "aesthetic-surgery") guide = { ...guide, navigation: [{"label":{"tr":"Yüz Estetiği","en":"Facial aesthetics"},"href":"/care/medical-aesthetics/facial-aesthetics"},{"label":{"tr":"Burun Cerrahisi","en":"Rhinoplasty"},"href":"/care/medical-aesthetics/rhinoplasty"},{"label":{"tr":"Meme Cerrahisi","en":"Breast surgery"},"href":"/care/medical-aesthetics/breast-surgery"},{"label":{"tr":"Vücut Şekillendirme","en":"Body contouring"},"href":"/care/medical-aesthetics/body-contouring"}] };
  if (Object.hasOwn(SURGERY_GUIDES, slug)) sections[sections.length - 1] = { ...sections[sections.length - 1], links: [{ label: text("Estetik Cerrahi rehberine dön", "Back to the Aesthetic Surgery guide"), href: "/care/medical-aesthetics/aesthetic-surgery" }] };
  if (slug === "healthcare-in-turkiye") sections.unshift({"title":{"tr":"Türkiye’de tedaviyi AURA ile değerlendirmek","en":"Considering treatment in Türkiye with AURA"},"body":{"tr":"Türkiye’nin sağlık altyapısını araştırırken kendi ihtiyacınızdan başlayın. AURA’da önce branş doktoruyla görüşebilir veya doğrudan Sağlık Turizmi talebi açabilirsiniz. Yapay zekâ destekli branş önerisinin ardından doktor değerlendirmesi, uygun görülürse tedavi planı ve acente teklifi gelir. Aşağıdaki ulusal bilgiler seçenekleri anlamanıza yardımcı olur; listelenen her kurumun AURA ile anlaşmalı olduğu anlamına gelmez. Size önerilen doktor, hastane ve hizmet kapsamı kendi dosyanızda ayrıca netleşir.","en":"Start with your own needs when researching Türkiye’s healthcare system. With AURA, begin with a specialist consultation or a direct Medical Tourism request. AI-assisted specialty suggestions lead into doctor assessment and, where appropriate, a treatment plan and agency proposal. The national information below provides context; it does not mean every listed institution is an AURA partner. Your proposed doctor, hospital and service scope are clarified in your own case."}});
  if (slug === "facts-and-figures") sections.unshift({"title":{"tr":"Bu veriler AURA başvurunuz için ne anlatır?","en":"What do these figures mean for your AURA request?"},"body":{"tr":"Bu sayfadaki sayılar Türkiye’nin sağlık sistemi ve uluslararası hasta hareketine aittir; AURA’nın doktor veya hastane ağı büyüklüğü değildir. AURA’da uygun branş, anlattığınız ihtiyaç üzerinden önerilir; doktor değerlendirmesi ve size sunulan tedavi planı kişisel dosyanız üzerinden ilerler. Ulusal hastane veya ziyaretçi sayısı, belirli bir işlemin sizin için uygunluğunu ya da bir tesisin AURA iş ortağı olduğunu göstermez. Kendi başvurunuzdaki doktoru, önerilen hastaneyi ve teklif kapsamını ayrıca inceleyin.","en":"These figures describe Türkiye’s healthcare system and international patient activity, not the size of AURA’s doctor or hospital network. AURA suggests a specialty based on your needs; doctor assessment and the proposed treatment plan proceed through your individual case. National hospital or visitor counts do not establish suitability for a procedure or that a facility partners with AURA. Review the doctor, proposed hospital and proposal scope in your own request."}});
  return [slug, withAestheticsJourney(slug, { ...guide, sections: slug === "healthcare-in-turkiye" ? [sections[0], ...SECTION_ORDER[slug].map(index => sections[index + 1])] : SECTION_ORDER[slug]?.map(index => sections[index]) ?? sections })];
}));
